"""OS-level environment variable materialization.

Writes env vars to the platform's persistent env store:
  macOS   : LaunchAgent plist + shell script  (~/Library/LaunchAgents)
  Linux   : systemd environment.d conf        (~/.config/environment.d)
  Windows : HKCU\\Environment registry + broadcast

All platform backends accept explicit path arguments so they can be
tested without touching the real filesystem -- pass a tmp_path directly.
"""

from __future__ import annotations

import sys
import xml.sax.saxutils as saxutils
from pathlib import Path


def detect_platform() -> str:
    if sys.platform == "darwin":
        return "macos"
    if sys.platform == "win32":
        return "windows"
    if sys.platform.startswith("linux"):
        try:
            if "microsoft" in Path("/proc/version").read_text().lower():
                return "wsl"
        except OSError:
            pass
        if Path("/run/systemd/system").exists():
            return "linux"
        raise RuntimeError(
            "non-systemd Linux is not supported for env materialization."
            " Only systemd-based distributions are supported."
        )
    raise RuntimeError(f"unsupported platform: {sys.platform!r}")


def materialize(*, env_vars: dict[str, str], dry_run: bool = False) -> None:
    """Persist env vars to the platform's persistent store.

    Args:
        env_vars: name -> expanded-value mapping.
        dry_run: if True, print what would be done without making changes.
    """
    platform = detect_platform()
    home = Path.home()

    if platform == "macos":
        _materialize_macos(env_vars=env_vars, dry_run=dry_run, home=home)
    elif platform in ("linux", "wsl"):
        _materialize_linux(env_vars=env_vars, dry_run=dry_run, home=home)
    elif platform == "windows":
        _materialize_windows(env_vars=env_vars, dry_run=dry_run)
    else:
        raise RuntimeError(f"materialize: unsupported platform {platform!r}")


# ── helpers ───────────────────────────────────────────────


def _expand(value: str) -> str:
    home = str(Path.home())
    return value.replace("${HOME}", home).replace("$HOME", home)


def _sh_escape(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def _systemd_escape(value: str) -> str:
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("$", "\\$")
    return f'"{value}"'


# ── macOS ─────────────────────────────────────────────────────


def _materialize_macos(*, env_vars: dict[str, str], dry_run: bool, home: Path) -> None:
    script_path = home / ".config" / "prescribe" / "login-env.sh"
    plist_path = home / "Library" / "LaunchAgents" / "com.prescribe.env.plist"
    plist_label = "com.prescribe.env"

    lines = [
        "#!/bin/sh",
        "# generated by prescribe -- do not edit by hand",
        "",
    ]
    for name, value in sorted(env_vars.items()):
        lines.append(f"launchctl setenv {name} {_sh_escape(value)}")
    lines.append("")
    script_content = "\n".join(lines)

    escaped_script_path = saxutils.escape(str(script_path))
    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{plist_label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>{escaped_script_path}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/tmp/prescribe-env.err</string>
    <key>StandardOutPath</key>
    <string>/tmp/prescribe-env.out</string>
</dict>
</plist>"""

    if dry_run:
        return

    script_path.parent.mkdir(parents=True, exist_ok=True)
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_content)
    script_path.chmod(0o755)
    plist_path.write_text(plist_content)

    _maybe_reload_launchctl(plist_path=plist_path, script_path=script_path)


def _maybe_reload_launchctl(
    *,
    plist_path: Path,
    script_path: Path,
) -> None:
    import subprocess

    errors: list[str] = []
    try:
        subprocess.run(["launchctl", "unload", str(plist_path)], capture_output=True)
    except FileNotFoundError:
        pass
    except Exception as exc:
        errors.append(f"launchctl unload failed: {exc}")

    try:
        result = subprocess.run(["launchctl", "load", str(plist_path)], capture_output=True, text=True)
        if result.returncode != 0:
            errors.append(f"launchctl load failed: {result.stderr.strip()}")
    except FileNotFoundError:
        pass
    except Exception as exc:
        errors.append(f"launchctl load failed: {exc}")

    try:
        subprocess.run(["/bin/sh", str(script_path)], capture_output=True)
    except Exception as exc:
        errors.append(f"shell script execution failed: {exc}")

    if errors:
        for err in errors:
            print(f"prescribe: {err}", file=sys.stderr)


# ── Linux ─────────────────────────────────────────────────────


def _materialize_linux(
    *,
    env_vars: dict[str, str],
    dry_run: bool,
    home: Path,
) -> None:
    conf_path = home / ".config" / "environment.d" / "prescribe.conf"
    lines = [
        "# generated by prescribe -- do not edit by hand",
        "",
    ]
    for name, value in sorted(env_vars.items()):
        lines.append(f"{name}={_systemd_escape(value)}")
    lines.append("")
    conf_content = "\n".join(lines)

    if dry_run:
        return

    conf_path.parent.mkdir(parents=True, exist_ok=True)
    conf_path.write_text(conf_content)

    _maybe_import_systemd(names=list(env_vars.keys()))


def _maybe_import_systemd(*, names: list[str]) -> None:
    import subprocess

    try:
        result = subprocess.run(
            ["systemctl", "--user", "import-environment", *names],
            capture_output=True,
            timeout=5,
        )
        if result.returncode != 0:
            stderr = result.stderr.decode("utf-8", errors="replace").strip()
            print(f"prescribe: systemctl import-environment failed: {stderr}", file=sys.stderr)
    except FileNotFoundError:
        pass
    except Exception as exc:
        print(f"prescribe: systemctl import-environment failed: {exc}", file=sys.stderr)


# ── Windows ───────────────────────────────────────────────────


def _materialize_windows(
    *,
    env_vars: dict[str, str],
    dry_run: bool,
) -> None:
    try:
        from winregenv import REG_EXPAND_SZ, RegistryRoot, broadcast_setting_change  # type: ignore[import-not-found]
    except ImportError as exc:
        raise RuntimeError("materialize on Windows requires winregenv. Install with: pip install winregenv") from exc

    if dry_run:
        return

    hkcu_env = RegistryRoot("HKCU", root_prefix="Environment")

    for name, value in sorted(env_vars.items()):
        vtype = REG_EXPAND_SZ if "%" in value else None
        hkcu_env.put_registry_value("", name, value, value_type=vtype)

    try:
        broadcast_setting_change("Environment")
    except Exception as exc:
        print(f"prescribe: broadcast_setting_change failed: {exc}", file=sys.stderr)
